In [1]:
import pandas as pd

In [16]:
df = pd.read_csv("../Datasets/tv2DF.csv", header=None)
print(df.head(53))

               0             1             2             3             4  \
0              0             1             2             3             4
1          <PAD>         <PAD>         <PAD>         <PAD>         <PAD>
2          <PAD>         <PAD>         <PAD>         <PAD>         <PAD>
3          <PAD>         <PAD>         <PAD>         <PAD>         <PAD>
4          <PAD>         <PAD>         <PAD>         <PAD>         <PAD>
5          <PAD>         <PAD>         <PAD>         <PAD>            46
6          <PAD>         <PAD>         <PAD>            46     lastbiler
7          <PAD>         <PAD>            46     lastbiler       leverer
8          <PAD>            46     lastbiler       leverer          sand
9             46     lastbiler       leverer          sand           til
10     lastbiler       leverer          sand           til    mesterskab
11       leverer          sand           til    mesterskab           NaN
12          sand           til    mesterskab           NaN            05
13           til    mesterskab           NaN            05          juni
14    mesterskab           NaN            05          juni          2018
15           NaN            05          juni          2018           kl.
16            05          juni          2018           kl.         16.25
17          juni          2018           kl.         16.25       billund
18          2018           kl.         16.25       billund        varmer
19           kl.         16.25       billund        varmer            op
20         16.25       billund        varmer            op           til
21       billund        varmer            op           til            de
22        varmer            op           til            de        danske
23            op           til            de        danske  mesterskaber
24           til            de        danske  mesterskaber             i
25            de        danske  mesterskaber             i  beachvolley.
26        danske  mesterskaber             i  beachvolley.           der
27  mesterskaber             i  beachvolley.           der       spilles
28             i  beachvolley.           der       spilles          også
29  beachvolley.           der       spilles          også      håndbold
30           der       spilles          også      håndbold             i
31       spilles          også      håndbold             i        sandet
32          også      håndbold             i        sandet       billund
33      håndbold             i        sandet       billund            er
34             i        sandet       billund            er          ikke
35        sandet       billund            er          ikke          just
36       billund            er          ikke          just         kendt
37            er          ikke          just         kendt           for
38          ikke          just         kendt           for  badestrande.
39          just         kendt           for  badestrande.           men
40         kendt           for  badestrande.           men             i
41           for  badestrande.           men             i           den
42  badestrande.           men             i           den      kommende
43           men             i           den      kommende       weekend
44             i           den      kommende       weekend            er
45           den      kommende       weekend            er          byen
46      kommende       weekend            er          byen          vært
47       weekend            er          byen          vært           for
48            er          byen          vært           for         årets
49          byen          vært           for         årets        danske
50          vært           for         årets        danske  mesterskaber
51           for         årets        danske  mesterskaber             i
52         årets        danske  mesterskaber             i  beachvolley.

               5             6             7
0              5             6             7
1          <PAD>         <PAD>         <PAD>
2          <PAD>         <PAD>            46
3          <PAD>            46     lastbiler
4             46     lastbiler       leverer
5      lastbiler       leverer          sand
6        leverer          sand           til
7           sand           til    mesterskab
8            til    mesterskab           NaN
9     mesterskab           NaN            05
10           NaN            05          juni
11            05          juni          2018
12          juni          2018           kl.
13          2018           kl.         16.25
14           kl.         16.25       billund
15         16.25       billund        varmer
16       billund        varmer            op
17        varmer            op           til
18            op           til            de
19           til            de        danske
20            de        danske  mesterskaber
21        danske  mesterskaber             i
22  mesterskaber             i  beachvolley.
23             i  beachvolley.           der
24  beachvolley.           der       spilles
25           der       spilles          også
26       spilles          også      håndbold
27          også      håndbold             i
28      håndbold             i        sandet
29             i        sandet       billund
30        sandet       billund            er
31       billund            er          ikke
32            er          ikke          just
33          ikke          just         kendt
34          just         kendt           for
35         kendt           for  badestrande.
36           for  badestrande.           men
37  badestrande.           men             i
38           men             i           den
39             i           den      kommende
40           den      kommende       weekend
41      kommende       weekend            er
42       weekend            er          byen
43            er          byen          vært
44          byen          vært           for
45          vært           for         årets
46           for         årets        danske
47         årets        danske  mesterskaber
48        danske  mesterskaber             i
49  mesterskaber             i  beachvolley.
50             i  beachvolley.             -
51  beachvolley.             -            vi
52             -            vi        hørte,

In [28]:
import os
current_dir = "/Users/lucasvilsen/Desktop/GrammatikTAK"
os.chdir("/Users/lucasvilsen/Downloads/dagw/sektioner/tv2r")
all_files = os.listdir(os.curdir)
print(all_files[0])
os.chdir(current_dir)

tv2r_121144

In [8]:
full_stop_len = len(df.iloc[(df[3].str[-1].values == ".") & (df[3].values != ".")])
comma_len = len(df.iloc[(df[3].str[-1].values == ",") & (df[3].values != ".")])
colon_len = len(df.iloc[(df[3].str[-1].values == ":") & (df[3].values != ".")])

In [9]:
print("full_stop_len: ", full_stop_len)
print("comma_len: ", comma_len)
print("colon_len: ", colon_len)

full_stop_len:  161460
comma_len:  159451
colon_len:  9666

In [18]:
full_and_comma_len = 50000
colon_len = 9000
total_len = 500000
rest_len = total_len - colon_len - full_and_comma_len * 2
rest_len

391000

In [19]:
full_stop = df.iloc[(df[3].str[-1].values == ".") & (df[3].values != ".")]
full_stop["label"] = 1
print(full_stop.head())
full_stop[3] = full_stop[3].map(lambda x: x[:-1])
print(full_stop.head())
comma = df.iloc[(df[3].str[-1].values == ",")]
comma["label"] = 2
comma[3] = comma[3].map(lambda x: x[:-1])
colon = df.iloc[(df[3].str[-1].values == ":")]
colon["label"] = 3
colon[3] = colon[3].map(lambda x: x[:-1])
rest = df.iloc[(df[3].str[-1].values != ".") & (df[3].str[-1].values != ",") & (df[3].str[-1].values != ":")]
rest["label"] = 0

/var/folders/pl/7f1cr2657p3bnpdt3bnm_9w00000gn/T/ipykernel_11932/1423500812.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_stop["label"] = 1
/var/folders/pl/7f1cr2657p3bnpdt3bnm_9w00000gn/T/ipykernel_11932/1423500812.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_stop[3] = full_stop[3].map(lambda x: x[:-1])

         0             1         2             3      4        5       6  \
16      05          juni      2018           kl.  16.25  billund  varmer
26  danske  mesterskaber         i  beachvolley.    der  spilles    også
39    just         kendt       for  badestrande.    men        i     den
53  danske  mesterskaber         i  beachvolley.      -       vi  hørte,
66     med            et  lignende  arrangement.     vi      har      et

           7  label
16        op      1
26  håndbold      1
39  kommende      1
53        at      1
66   område,      1
         0             1         2            3      4        5       6  \
16      05          juni      2018           kl  16.25  billund  varmer
26  danske  mesterskaber         i  beachvolley    der  spilles    også
39    just         kendt       for  badestrande    men        i     den
53  danske  mesterskaber         i  beachvolley      -       vi  hørte,
66     med            et  lignende  arrangement     vi      har      et

           7  label
16        op      1
26  håndbold      1
39  kommende      1
53        at      1
66   område,      1

/var/folders/pl/7f1cr2657p3bnpdt3bnm_9w00000gn/T/ipykernel_11932/1423500812.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comma["label"] = 2
/var/folders/pl/7f1cr2657p3bnpdt3bnm_9w00000gn/T/ipykernel_11932/1423500812.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comma[3] = comma[3].map(lambda x: x[:-1])
/var/folders/pl/7f1cr2657p3bnpdt3bnm_9w00000gn/T/ipykernel_11932/1423500812.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colon["label"] = 3
/var/folders/pl/7f1cr2657p3bnpdt3bnm_9w00000gn/T/ipykernel_11932/1423500812.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colon[3] = colon[3].map(lambda x: x[:-1])
/var/folders/pl/7f1cr2657p3bnpdt3bnm_9w00000gn/T/ipykernel_11932/1423500812.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rest["label"] = 0

In [20]:
data_frames = [full_stop[:full_and_comma_len], comma[:full_and_comma_len], colon[:colon_len], rest[:rest_len]]
df_merged = pd.concat(data_frames)

In [21]:
full_stop[:full_and_comma_len]

,0,1,2,3,4,5,6,7,label
16,05,juni,2018,kl,16.25,billund,varmer,op,1
26,danske,mesterskaber,i,beachvolley,der,spilles,også,håndbold,1
39,just,kendt,for,badestrande,men,i,den,kommende,1
53,danske,mesterskaber,i,beachvolley,-,vi,"hørte,",at,1
66,med,et,lignende,arrangement,vi,har,et,"område,",1
...,...,...,...,...,...,...,...,...,...
815118,tale,om,en,forbrydelse,-,det,er,der,1
815133,pedersen,ved,sydøstjyllands,politi,kvinden,er,tilsyneladende,faldet,1
815158,ligsynet,senere,i,dag,esbjerg-profil:,vi,kan,vinde,1
815167,11,august,2013,kl,06.12,esbjerg-angriberen,martin,braithwaite,1
815183,til,medaljekandidat,i,superligaen,med,en,knusende,sikker,1

In [22]:
print(df_merged)

             0             1         2            3      4           5  \
16          05          juni      2018           kl  16.25     billund
26      danske  mesterskaber         i  beachvolley    der     spilles
39        just         kendt       for  badestrande    men           i
53      danske  mesterskaber         i  beachvolley      -          vi
66         med            et  lignende  arrangement     vi         har
...        ...           ...       ...          ...    ...         ...
447240     til        april,    kommer          det    til          at
447241  april,        kommer       det          til     at          gå
447242  kommer           det       til           at     gå          ud
447243     det           til        at           gå     ud        over
447244     til            at        gå           ud   over  plejehjem,

                    6              7  label
16             varmer             op      1
26               også       håndbold      1
39                den       kommende      1
53             hørte,             at      1
66                 et        område,      1
...               ...            ...    ...
447240             gå             ud      0
447241             ud           over      0
447242           over     plejehjem,      0
447243     plejehjem,  institutioner      0
447244  institutioner             og      0

[500000 rows x 9 columns]

In [32]:
print(os.getcwd())
print(os.listdir(os.curdir))
df_merged.to_csv("Datasets/tv2DF_labeled.csv", encoding="UTF-8", index=False, header=None)

/Users/lucasvilsen/Desktop/GrammatikTAK
['GoogleAppEngine', '.DS_Store', 'tmp_trainer', 'modelPunctuation', 'FineTuneBertModel.py', 'modelCombined4', 'DataProcessing', 'modelCombined3', 'FullCheck.py', 'modelCombined2', 'Datasets', 'Other', 'modelCombined', 'output', 'Testing.ipynb', 'GoogleExtension', 'results', 'modelComma', 'optimzing_load.py', 'FineTuneBert.py', 'model', 'Spellchecker.py', '.ipynb_checkpoints', 'NER-model.py', '.vscode', 'UseFineTunedModel.py', 'outputs', 'testing_google_cloud.py']